name: Rebase Pull Request

on:
  repository_dispatch:
    types: [rebase-command]

jobs:
  rebase_pull_request:
    name: Rebase Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Pull Request
        uses: peter-evans/rebase@e52a872cdca7af7b864ee7fed6dfc029013abd3c
        id: rebase
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          head: ${{ github.event.client_payload.pull_request.head.label }}

      - name: Add üëç Reaction
        if: always() && steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: '+1'

      - name: Add üëé Reaction
        if: always() && steps.rebase.outputs.rebased-count != 1
        uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: '-1'
